# Generated by Django 4.1.3 on 2023-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccionusuario',
            name='ultima',
            field=models.BooleanField(default=False, verbose_name='Última lección vista por el usuario'),
        ),
    ]
