# Generated by Django 4.1.3 on 2023-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_curso_num_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='Debe ser escrito todo en minúsculas y sin espacios', null=True, unique=True, verbose_name='Slug del curso'),
        ),
    ]
