# Generated by Django 4.1.3 on 2023-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_alter_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='slug',
            field=models.SlugField(blank=True, help_text='Debe ser escrito todo en minúsculas y sin espacios', null=True, unique=True, verbose_name='Slug de la lección'),
        ),
    ]
