# Generated by Django 4.1.3 on 2024-08-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_custom', '0003_alter_usuario_options'),
        ('curso', '0009_alter_leccion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario_custom.usuario', verbose_name='Profesor del curso'),
        ),
    ]
