# Generated by Django 4.1.3 on 2023-06-28 18:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='salud/')),
                ('imagen_miniatura', models.ImageField(blank=True, null=True, upload_to='salud/')),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='salud/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='salud/')),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Artículo de Salud',
                'verbose_name_plural': 'Artículos de Salud',
            },
        ),
        migrations.CreateModel(
            name='ItemSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_item', models.PositiveSmallIntegerField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.salud')),
            ],
            options={
                'verbose_name': 'Ítem Salud',
                'verbose_name_plural': 'Ítems Salud',
            },
        ),
    ]
