# Generated by Django 4.1.3 on 2024-08-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_custom', '0002_usuario_compro_gestoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
