# Generated by Django 4.1.3 on 2024-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_custom', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
