# Generated by Django 4.1.3 on 2023-06-28 18:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_principal', models.ImageField(upload_to='recetas/')),
                ('imagen_miniatura', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ingredientes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('composicion_nutricional', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('duracion', models.IntegerField(blank=True)),
                ('imagen_secundaria_1', models.ImageField(blank=True, upload_to='recetas/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, upload_to='recetas/')),
                ('imagen_secundaria_3', models.ImageField(blank=True, upload_to='recetas/')),
                ('youtube_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='PasoReceta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_paso', models.PositiveSmallIntegerField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.receta')),
            ],
            options={
                'verbose_name': 'Paso receta',
                'verbose_name_plural': 'Pasos receta',
            },
        ),
    ]
