# Generated by Django 4.1.3 on 2023-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_remove_receta_youtube_link_receta_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen_secundaria_4',
            field=models.ImageField(blank=True, upload_to='recetas/'),
        ),
    ]
