# Generated by Django 4.1.3 on 2023-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_principal', models.ImageField(upload_to='media/recetas/')),
                ('resumen', models.TextField(blank=True)),
                ('ingredientes', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('composicion_nutricional', models.TextField(blank=True)),
                ('duracion', models.IntegerField(blank=True)),
                ('imagen_secundaria_1', models.ImageField(blank=True, upload_to='media/recetas/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, upload_to='media/recetas/')),
                ('imagen_secundaria_3', models.ImageField(blank=True, upload_to='media/recetas/')),
                ('youtube_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Modelo base',
                'verbose_name_plural': 'Modelos base',
                'abstract': False,
            },
        ),
    ]
