# Generated by Django 4.1.3 on 2022-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='imagen',
            new_name='imagen_principal',
        ),
        migrations.AddField(
            model_name='receta',
            name='composicion_nutricional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_secundaria_4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receta',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
