# Generated by Django 4.1.3 on 2023-01-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_rename_imagen_receta_imagen_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='imagen_secundaria_4',
            new_name='imagen_secundaria_3',
        ),
    ]
