# Generated by Django 4.1.3 on 2023-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_alter_receta_options_remove_receta_instrucciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoreceta',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='pasoreceta',
            name='deleting_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AlterField(
            model_name='pasoreceta',
            name='updating_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='deleting_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='updating_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
    ]
