# Generated by Django 4.1.3 on 2023-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Artículo de Salud',
                'verbose_name_plural': 'Artículos de Salud',
            },
        ),
    ]
