# Generated by Django 4.1.3 on 2023-03-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salud',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salud',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AddField(
            model_name='salud',
            name='deleting_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AddField(
            model_name='salud',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='salud/'),
        ),
        migrations.AddField(
            model_name='salud',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='salud/'),
        ),
        migrations.AddField(
            model_name='salud',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='salud/'),
        ),
        migrations.AddField(
            model_name='salud',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salud',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salud',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='salud',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salud',
            name='updating_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AddField(
            model_name='salud',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ItemSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_item', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
                ('salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.salud')),
            ],
            options={
                'verbose_name': 'Ítem Salud',
                'verbose_name_plural': 'Ítems Salud',
            },
        ),
    ]
