# Generated by Django 4.1.3 on 2022-12-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salud',
            options={'verbose_name': 'Artículo de Salud', 'verbose_name_plural': 'Artículos de Salud'},
        ),
    ]
