# Generated by Django 4.1.3 on 2023-04-16 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_salud_conclusion_salud_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsalud',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='salud',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salud',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salud',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
