# Generated by Django 4.1.3 on 2023-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_alter_itemsalud_descripcion_alter_salud_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salud',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='salud/'),
        ),
    ]
