# Generated by Django 4.1.3 on 2023-06-08 15:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='nutricion/')),
                ('imagen_miniatura', models.ImageField(blank=True, null=True, upload_to='nutricion/')),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('texto_cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='nutricion/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='nutricion/')),
                ('texto_explicativo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Artículo de Nutrición',
                'verbose_name_plural': 'Artículos de Nutrición',
            },
        ),
    ]
