# Generated by Django 4.1.3 on 2023-03-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='deleting_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='nutricion/'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='nutricion/'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='nutricion/'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='texto_cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='texto_explicativo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='updating_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
