# Generated by Django 4.1.3 on 2022-12-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutricion',
            options={'verbose_name_plural': 'Artículos de nutrición'},
        ),
    ]
