# Generated by Django 4.1.3 on 2022-12-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_alter_nutricion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutricion',
            options={'verbose_name': 'Artículo de Nutrición', 'verbose_name_plural': 'Artículos de Nutrición'},
        ),
    ]
