# Generated by Django 4.1.3 on 2023-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_alter_nutricion_intro_alter_nutricion_resumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='nutricion/'),
        ),
    ]
