# Generated by Django 4.1.3 on 2023-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_remove_nutricion_youtube_link_nutricion_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='imagen_secundaria_3',
            field=models.ImageField(blank=True, null=True, upload_to='nutricion/'),
        ),
    ]
