# Generated by Django 4.1.3 on 2023-06-08 15:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaCocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='escuela_cocina/')),
                ('imagen_miniatura', models.ImageField(blank=True, null=True, upload_to='escuela_cocina/')),
                ('resumen', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('ingredientes', ckeditor.fields.RichTextField(blank=True, default='')),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='escuela_cocina/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='escuela_cocina/')),
                ('imagen_secundaria_3', models.ImageField(blank=True, null=True, upload_to='escuela_cocina/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Artículo de Escuela de Cocina',
                'verbose_name_plural': 'Artículos de Escuela de Cocina',
            },
        ),
        migrations.CreateModel(
            name='PasoTecnica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_paso', models.PositiveSmallIntegerField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('escuela_cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela_cocina.escuelacocina')),
            ],
            options={
                'verbose_name': 'Paso técnica',
                'verbose_name_plural': 'Pasos técnica',
            },
        ),
    ]
