# Generated by Django 4.1.3 on 2022-12-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuelacocina',
            options={'verbose_name': 'Artículo de Escuela de Cocina', 'verbose_name_plural': 'Artículos de Escuela de Cocina'},
        ),
    ]
