# Generated by Django 4.1.3 on 2023-03-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuelacocina',
            name='imagen',
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='deleting_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='escuela_cocina/'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='escuela_cocina/'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='escuela_cocina/'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='imagen_secundaria_3',
            field=models.ImageField(blank=True, null=True, upload_to='escuela_cocina/'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='updating_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización'),
        ),
        migrations.AddField(
            model_name='escuelacocina',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escuelacocina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escuelacocina',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasoTecnica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_paso', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
                ('escuela_cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela_cocina.escuelacocina')),
            ],
            options={
                'verbose_name': 'Paso técnica',
                'verbose_name_plural': 'Pasos técnica',
            },
        ),
    ]
