# Generated by Django 4.1.3 on 2023-04-16 14:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0002_remove_escuelacocina_imagen_escuelacocina_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelacocina',
            name='conclusion',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='escuelacocina',
            name='ingredientes',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='escuelacocina',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
