# Generated by Django 4.1.3 on 2023-04-16 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0003_alter_escuelacocina_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasotecnica',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
