# Generated by Django 4.1.3 on 2023-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0003_remove_escuelacocina_youtube_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelacocina',
            name='slug',
            field=models.SlugField(blank=True, help_text='Debe ser escrito todo en minúsculas y sin espacios', null=True, unique=True, verbose_name='Slug del artículo'),
        ),
    ]
