# Generated by Django 4.1.3 on 2023-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_cocina', '0004_alter_pasotecnica_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelacocina',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='escuela_cocina/'),
        ),
    ]
