# Generated by Django 4.1.3 on 2023-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_leccion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='video',
        ),
        migrations.AddField(
            model_name='leccion',
            name='video_id',
            field=models.CharField(blank=True, help_text='Insertar el id del video de la lección', max_length=20, null=True, verbose_name='Video de la lección'),
        ),
    ]
