# Generated by Django 4.1.3 on 2023-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_remove_leccion_video_leccion_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='slug',
            field=models.SlugField(blank=True, help_text='Debe ser escrito todo en minúsculas y sin espacios', null=True, verbose_name='Slug de la lección'),
        ),
    ]
