# Generated by Django 4.1.3 on 2023-04-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe del movimiento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_custom.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
