# Generated by Django 4.1.3 on 2023-06-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('usuario_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre del mdp')),
                ('tipo', models.IntegerField(choices=[(0, 'NINGUNO'), (1, 'PAYPAL')], default=0, verbose_name='Tipo del mdp')),
                ('client_id', models.CharField(max_length=150)),
                ('secret_key', models.CharField(max_length=300)),
                ('moneda_codigo', models.CharField(max_length=5, verbose_name='Código de la moneda')),
                ('test', models.BooleanField(default=True, verbose_name='Medio de prueba')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe del movimiento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del movimiento')),
                ('condicion', models.IntegerField(choices=[(0, 'INICIADA'), (1, 'FINALIZADA'), (2, 'NO FINALIZADA')], default=0, verbose_name='Estado del movimiento')),
                ('codigo_operacion', models.CharField(max_length=20, null=True, verbose_name='Código operación')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('medio_de_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.mediodepago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_custom.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
