# Generated by Django 4.1.3 on 2023-06-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_leccion_slug'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha eliminación')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre del mdp')),
                ('tipo', models.IntegerField(choices=[(0, 'NINGUNO'), (1, 'PAYPAL')], default=0, verbose_name='Tipo del mdp')),
                ('client_id', models.CharField(max_length=150)),
                ('secret_key', models.CharField(max_length=300)),
                ('moneda_codigo', models.CharField(max_length=5, verbose_name='Código de la moneda')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='codigo_operacion',
            field=models.CharField(max_length=20, null=True, verbose_name='Código operación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='condicion',
            field=models.IntegerField(choices=[(0, 'INICIADA'), (1, 'FINALIZADA'), (2, 'NO FINALIZADA')], default=0, verbose_name='Estado del movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='medio_de_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.mediodepago'),
        ),
    ]
