# Generated by Django 4.1.3 on 2024-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='compro_gestoria',
            field=models.BooleanField(default=False, verbose_name='Compró gestoría'),
        ),
    ]
