# Generated by Django 4.1.3 on 2023-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_mediodepago_movimiento_codigo_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='test',
            field=models.BooleanField(default=True, verbose_name='Medio de prueba'),
        ),
    ]
